// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';

import { CloseIcon } from './CloseIcon.tsx';

const meta = {
  title: 'Icons/components/CloseIcon',
  component: CloseIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof CloseIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
