// this file was generated by the generateIconComponents.cjs script
export const CloseIcon = () => {
    return (
    <span className="icon icon-close">
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   viewBox="0 0 280 280"
   version="1.1"
   id="svg1"
   sodipodi:docname="close.svg"
   inkscape:version="1.3.2 (091e20e, 2023-11-25)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs1" />
  <sodipodi:namedview
     id="namedview1"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="0.25"
     inkscape:showpageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     inkscape:deskcolor="#d1d1d1"
     inkscape:zoom="1.5420565"
     inkscape:cx="162.76965"
     inkscape:cy="144.28784"
     inkscape:window-width="1888"
     inkscape:window-height="980"
     inkscape:window-x="0"
     inkscape:window-y="25"
     inkscape:window-maximized="0"
     inkscape:current-layer="g1" />
  <g
     id="g1">
    <path
       id="svg_4"
       d="M 24.754639,14.661707 12.795276,26.565838 C -7.0183553,46.290419 3.4948746,67.690128 23.554159,87.133341 L 76.002874,137.97177 24.278162,188.6358 C 4.3028983,208.20127 -6.2015879,229.7481 13.696673,249.35126 l 12.008273,11.83297 c 19.898264,19.60317 41.778863,9.42929 61.754249,-10.13629 l 52.325495,-51.25401 53.26452,51.62891 c 20.05981,19.44364 42.06941,29.56658 61.88308,9.84204 l 11.95935,-11.90412 c 19.81366,-19.72459 9.30088,-41.12384 -10.75888,-60.56752 l -52.83282,-51.21042 52.9449,-51.859014 C 276.22068,66.157738 286.72626,44.609849 266.82802,25.006669 L 254.81805,13.175372 C 234.91979,-6.427799 213.04136,3.74396 193.06549,23.310003 L 139.51814,75.760659 86.637713,24.503742 C 66.578514,5.060681 44.568275,-5.062871 24.754639,14.661707 Z"
       style="stroke-width:1.21712" />
  </g>
</svg>

    </span>
    );
}