// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';

import { FastForwardIcon } from './FastForwardIcon.tsx';

const meta = {
  title: 'Icons/components/FastForwardIcon',
  component: FastForwardIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof FastForwardIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
