
// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';
// import { fn } from '@storybook/test';

import { GithubIcon } from './GithubIcon';

const meta = {
  title: 'Icons/GithubIcon',
  component: GithubIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof GithubIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
