
// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';
// import { fn } from '@storybook/test';

import { LinkedinIcon } from './LinkedinIcon';

const meta = {
  title: 'Icons/LinkedinIcon',
  component: LinkedinIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof LinkedinIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
