// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';

import { LinkedinIcon } from './LinkedinIcon.tsx';

const meta = {
  title: 'Icons/components/LinkedinIcon',
  component: LinkedinIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof LinkedinIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
