
// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';

import { LoveIcon } from './LoveIcon.tsx';

const meta = {
  title: 'Icons/components/LoveIcon',
  component: LoveIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof LoveIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
