
// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';

import { PauseIcon } from './PauseIcon.tsx';

const meta = {
  title: 'Icons/components/PauseIcon',
  component: PauseIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof PauseIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
