// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';

import { PlayIcon } from './PlayIcon.tsx';

const meta = {
  title: 'Icons/components/PlayIcon',
  component: PlayIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof PlayIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
