// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';

import { RewindIcon } from './RewindIcon.tsx';

const meta = {
  title: 'Icons/components/RewindIcon',
  component: RewindIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof RewindIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
