
// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';

import { StopIcon } from './StopIcon.tsx';

const meta = {
  title: 'Icons/components/StopIcon',
  component: StopIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof StopIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
