// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';

import { StorybookIcon } from './StorybookIcon.tsx';

const meta = {
  title: 'Icons/components/StorybookIcon',
  component: StorybookIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof StorybookIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
