
// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';
// import { fn } from '@storybook/test';

import { FastForwardIcon } from '../../icons/FastForwardIcon';

const meta = {
  title: 'Icons/FastForwardIcon',
  component: FastForwardIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof FastForwardIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
