
// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';
// import { fn } from '@storybook/test';

import { PauseIcon } from '../../icons/PauseIcon';

const meta = {
  title: 'Icons/PauseIcon',
  component: PauseIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof PauseIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
