
// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';
// import { fn } from '@storybook/test';

import { RewindIcon } from '../../icons/RewindIcon';

const meta = {
  title: 'Icons/RewindIcon',
  component: RewindIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof RewindIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
