
// this file was generated by the generateIconComponents.cjs script
import type { Meta, StoryObj } from '@storybook/react';
// import { fn } from '@storybook/test';

import { StopIcon } from '../../icons/StopIcon';

const meta = {
  title: 'Icons/StopIcon',
  component: StopIcon,
  tags: ['autodocs'],
  parameters: {},
  args: {},
} satisfies Meta<typeof StopIcon>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
